# Generated by Django 5.1.6 on 2025-02-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$UC2ZYiKZXNJ4owJ0PozPhX$hG/IpQ3TMwGfybajaDnxoebd2SUwo4cW8n10HoYqqEM=', max_length=10000),
        ),
    ]
