# Generated by Django 5.1.6 on 2025-02-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$atWEQYvOlCB5VtlHwQejFM$bcUxfnbR7wkk8+4YFRVBqW1g4bdhhF5SrK/MwY6T2Bc=', max_length=10000),
        ),
    ]
