# Generated by Django 5.1.6 on 2025-02-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$FTLi3C9rKyowyVE4VmpHY2$VlIUeMaxWMI9hInfUbnaC+UVgCqzRzy6Q2x/7Ti4ZZQ=', max_length=10000),
        ),
    ]
