# Generated by Django 5.1.6 on 2025-02-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Mwd1F10CyL0251dsi9603R$TGm2agNrZqXf7Wm9H0lU1CF5aA8oaN9FYPrdiAaxqGQ=', max_length=10000),
        ),
    ]
