# Generated by Django 5.1.6 on 2025-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$hLFJF6iBFgpM7vEREOVG11$Hn32xotyP3gS1gsfgrZYFBNq5qOexV/cjy4zMvE5A6M=', max_length=10000),
        ),
    ]
