# Generated by Django 5.1.6 on 2025-02-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$6fQq3c2Qi11CGQ2rW2AuJL$BlpyuIlJarg/Psrx+ADBofIUBgc9GNN4YJzfFXm2yvE=', max_length=10000),
        ),
    ]
