# Generated by Django 5.1.6 on 2025-02-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$SO009KPqN7OqUeM4pnDWCL$CgBaQBTO0u8dnN6YHccIX4s58+c2TNT3R6JfREBZrU4=', max_length=10000),
        ),
    ]
