# Generated by Django 5.1.6 on 2025-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$QXYsxY3pm8GzcYoOlixU7y$UPpd7zqa7nVVwD0zbsYILza8e2v5qccDyKilgOrxcMU=', max_length=10000),
        ),
    ]
