# Generated by Django 5.1.6 on 2025-02-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$kWAD8aexKXexdB5aok1lNd$/aV1/NnEqDWJo/CD44DnruMC80x+yomjxP3hLObttLc=', max_length=10000),
        ),
    ]
