# Generated by Django 5.1.6 on 2025-02-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='d5ee46f372ca', max_length=20, unique=True),
        ),
    ]
