# Generated by Django 5.1.6 on 2025-02-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='3e1a61a8abe0', max_length=20, unique=True),
        ),
    ]
