# Generated by Django 5.1.6 on 2025-02-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='2f5aa56e3f1d', max_length=20, unique=True),
        ),
    ]
