# Generated by Django 5.1.6 on 2025-02-16 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_payment_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='Store.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='0728846c298e', max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'dish')},
        ),
    ]
