# Generated by Django 5.1.6 on 2025-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='264589ea3513486e912e5b7496894daf', max_length=32, unique=True),
        ),
    ]
