# Generated by Django 5.1.6 on 2025-02-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_dish_featured_alter_dish_image_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='5610daa336f648799c22ce7cc065d757', max_length=32, unique=True),
        ),
    ]
