# Generated by Django 5.1.6 on 2025-03-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='44bc83b421e64b1dbcb6575c57fbe159', max_length=32, unique=True),
        ),
    ]
