# Generated by Django 5.1.6 on 2025-03-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='9e1b6dcf12a840c3a47e737595abb21f', max_length=32, unique=True),
        ),
    ]
