# Generated by Django 5.1.6 on 2025-03-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='f194182f5e814af49c95af68f1b315bd', max_length=32, unique=True),
        ),
    ]
